/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.118
 * Generated at: 2026-06-24 01:43:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.myshop.entity.*;
import com.myshop.entity.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.LinkedHashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1782265415179L));
    _jspx_dependants.put("/includes/footer.jsp", Long.valueOf(1782219284998L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.myshop.entity");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.myshop.entity.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    if (request.getAttribute("categoryTree") == null) {
        request.getRequestDispatcher("/index").forward(request, response);
        return;
    }
    Map<Category, List<Category>> categoryTree = (Map<Category, List<Category>>) request.getAttribute("categoryTree");
    List<Goods> hotGoods = (List<Goods>) request.getAttribute("hotGoods");
    List<Goods> newGoods = (List<Goods>) request.getAttribute("newGoods");
    if (categoryTree == null) categoryTree = new LinkedHashMap<>();
    if (hotGoods == null) hotGoods = new ArrayList<>();
    if (newGoods == null) newGoods = new ArrayList<>();

    List<Category> topCategories = new ArrayList<>();
    for (Map.Entry<Category, List<Category>> entry : categoryTree.entrySet()) {
        if (entry.getKey().getPid() == 0) topCategories.add(entry.getKey());
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zh-CN\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>MyShop — Modern E-Commerce</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/css/global.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write('\n');
      out.write('\n');

    User sessionUser = (User) session.getAttribute("user");
    Integer cartCount = (Integer) request.getAttribute("cartCount");
    if (cartCount == null) cartCount = 0;
    String currentPath = request.getRequestURI();

      out.write("\n");
      out.write("<header class=\"site-header\" id=\"siteHeader\">\n");
      out.write("    <div class=\"header-inner\">\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/\" class=\"header-logo\">MY<span>SHOP</span></a>\n");
      out.write("        <nav class=\"nav-main\" id=\"navMain\">\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/\">Home</a>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp\">Shop</a>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp?sort=sales\">Best Sellers</a>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp?sort=newest\">New Arrivals</a>\n");
      out.write("        </nav>\n");
      out.write("        <div class=\"header-actions\">\n");
      out.write("            ");
 if (sessionUser != null) { 
      out.write("\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/profile.jsp\" class=\"icon-btn\" title=\"My Account\">&#x1F464;</a>\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/login.jsp\" class=\"icon-btn\" title=\"Login\">&#x1F464;</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/cart/index.jsp\" class=\"icon-btn cart-icon\" title=\"Cart\">&#x1F6D2;\n");
      out.write("                <span class=\"cart-badge ");
      out.print( cartCount > 0 ? "show" : "" );
      out.write("\" id=\"cartBadge\">");
      out.print( cartCount > 0 ? cartCount : "" );
      out.write("</span>\n");
      out.write("            </a>\n");
      out.write("            <div class=\"hamburger\" id=\"hamburger\" onclick=\"toggleMenu()\">\n");
      out.write("                <span></span><span></span><span></span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <nav class=\"mobile-nav\" id=\"mobileNav\">\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/\">Home</a>\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp\">Shop</a>\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp?sort=sales\">Best Sellers</a>\n");
      out.write("        <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp?sort=newest\">New Arrivals</a>\n");
      out.write("        ");
 if (sessionUser != null) { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/profile.jsp\">My Account</a>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/logout\">Sign Out</a>\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/login.jsp\">Sign In</a>\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/user/register.jsp\">Register</a>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </nav>\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Hero Banner -->\n");
      out.write("<section class=\"hero\" id=\"hero\">\n");
      out.write("    <div class=\"hero-slider\" id=\"heroSlider\">\n");
      out.write("        <div class=\"hero-slide\">\n");
      out.write("            <div class=\"hero-content\">\n");
      out.write("                <h2>Summer Collection 2026</h2>\n");
      out.write("                <p>Discover refined essentials designed for the modern lifestyle. Minimalist aesthetics, maximum comfort.</p>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp?categoryId=1\" class=\"hero-cta\">Explore Collection</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"hero-slide\">\n");
      out.write("            <div class=\"hero-content\">\n");
      out.write("                <h2>Fresh Harvest</h2>\n");
      out.write("                <p>Farm-to-table quality. Handpicked seasonal fruits and vegetables delivered to your doorstep.</p>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp?categoryId=5\" class=\"hero-cta\">Shop Fresh</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"hero-slide\">\n");
      out.write("            <div class=\"hero-content\">\n");
      out.write("                <h2>Digital Life</h2>\n");
      out.write("                <p>Premium gadgets and accessories that elevate how you work and play.</p>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp?categoryId=21\" class=\"hero-cta\">View All</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"hero-dots\" id=\"heroDots\">\n");
      out.write("        <span class=\"hero-dot active\" data-index=\"0\"></span>\n");
      out.write("        <span class=\"hero-dot\" data-index=\"1\"></span>\n");
      out.write("        <span class=\"hero-dot\" data-index=\"2\"></span>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"hero-arrows\">\n");
      out.write("        <button class=\"hero-arrow\" onclick=\"heroPrev()\">&#10094;</button>\n");
      out.write("        <button class=\"hero-arrow\" onclick=\"heroNext()\">&#10095;</button>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- Category Grid -->\n");
      out.write("<section class=\"section\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"section-header\">\n");
      out.write("            <h2>Shop by Category</h2>\n");
      out.write("            <p>Find what you need, discover what you love</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"category-grid\">\n");
      out.write("            ");
 for (Category cat : topCategories) {
                String bgImg = "";
                for (Map.Entry<Category, List<Category>> e : categoryTree.entrySet()) {
                    if (e.getKey().getId() == cat.getId() && !e.getValue().isEmpty()) {
                        bgImg = e.getValue().get(0).getPicture();
                        break;
                    }
                }
            
      out.write("\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp?categoryId=");
      out.print( cat.getId() );
      out.write("\" class=\"category-card\">\n");
      out.write("                <img src=\"");
      out.print( request.getContextPath() );
      out.write('/');
      out.print( bgImg );
      out.write("\" alt=\"");
      out.print( cat.getName() );
      out.write("\" onerror=\"this.style.display='none'\">\n");
      out.write("                <div class=\"category-card-overlay\">\n");
      out.write("                    <h3>");
      out.print( cat.getName() );
      out.write("</h3>\n");
      out.write("                    <span>Shop Now →</span>\n");
      out.write("                </div>\n");
      out.write("            </a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- Hot Products -->\n");
      out.write("<section class=\"section\" style=\"background: var(--c-bg);\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"section-header\">\n");
      out.write("            <h2>Best Sellers</h2>\n");
      out.write("            <p>Our most popular products, loved by customers</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"product-grid\">\n");
      out.write("            ");
 for (Goods g : hotGoods) { 
      out.write("\n");
      out.write("            <div class=\"product-card\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/goods/detail?id=");
      out.print( g.getId() );
      out.write("'\">\n");
      out.write("                <div class=\"product-card-image\">\n");
      out.write("                    ");
 if (g.getIsNew() == 1) { 
      out.write("<span class=\"tag-new\">NEW</span>");
 } 
      out.write("\n");
      out.write("                    <img src=\"");
      out.print( request.getContextPath() );
      out.write('/');
      out.print( g.getPicture() );
      out.write("\" alt=\"");
      out.print( g.getName() );
      out.write("\" onerror=\"this.src='data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22300%22 height=%22300%22><rect fill=%22%23f5f5f5%22 width=%22300%22 height=%22300%22/><text x=%22150%22 y=%22150%22 text-anchor=%22middle%22 fill=%22%23ccc%22 font-size=%2214%22>No Image</text></svg>'\">\n");
      out.write("                    <div class=\"product-card-actions\" onclick=\"event.stopPropagation()\">\n");
      out.write("                        <button onclick=\"addToCart(");
      out.print( g.getId() );
      out.write(", 1)\" title=\"Add to Cart\">+</button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-card-name\">");
      out.print( g.getName() );
      out.write("</div>\n");
      out.write("                <div class=\"product-card-price\">¥");
      out.print( String.format("%.2f", g.getPrice()) );
      out.write("</div>\n");
      out.write("                <div class=\"product-card-meta\">Sold ");
      out.print( g.getSales() );
      out.write(" &middot; Stock ");
      out.print( g.getStock() );
      out.write("</div>\n");
      out.write("            </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- New Arrivals -->\n");
      out.write("<section class=\"section\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"section-header\">\n");
      out.write("            <h2>New Arrivals</h2>\n");
      out.write("            <p>Fresh picks, just landed</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"new-scroll\">\n");
      out.write("            ");
 for (Goods g : newGoods) { 
      out.write("\n");
      out.write("            <div class=\"product-card\" onclick=\"location.href='");
      out.print( request.getContextPath() );
      out.write("/goods/detail?id=");
      out.print( g.getId() );
      out.write("'\">\n");
      out.write("                <div class=\"product-card-image\">\n");
      out.write("                    <span class=\"tag-new\">NEW</span>\n");
      out.write("                    <img src=\"");
      out.print( request.getContextPath() );
      out.write('/');
      out.print( g.getPicture() );
      out.write("\" alt=\"");
      out.print( g.getName() );
      out.write("\">\n");
      out.write("                    <div class=\"product-card-actions\" onclick=\"event.stopPropagation()\">\n");
      out.write("                        <button onclick=\"addToCart(");
      out.print( g.getId() );
      out.write(", 1)\" title=\"Add to Cart\">+</button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"product-card-name\">");
      out.print( g.getName() );
      out.write("</div>\n");
      out.write("                <div class=\"product-card-price\">¥");
      out.print( String.format("%.2f", g.getPrice()) );
      out.write("</div>\n");
      out.write("                <div class=\"product-card-meta\">");
      out.print( g.getSpec() );
      out.write("</div>\n");
      out.write("            </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"site-footer\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"footer-grid\">\n");
      out.write("            <div class=\"footer-col\">\n");
      out.write("                <h4>MYSHOP</h4>\n");
      out.write("                <p>A modern e-commerce platform built with care. We deliver quality products with exceptional service.</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer-col\">\n");
      out.write("                <h4>Shop</h4>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp?categoryId=21\">Mobile & Digital</a>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp?categoryId=1\">Fashion</a>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp?categoryId=5\">Food & Drinks</a>\n");
      out.write("                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/goods/list.jsp?categoryId=11\">Jewelry</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer-col\">\n");
      out.write("                <h4>About</h4>\n");
      out.write("                <a href=\"#\">Our Story</a>\n");
      out.write("                <a href=\"#\">Careers</a>\n");
      out.write("                <a href=\"#\">Press</a>\n");
      out.write("                <a href=\"#\">Sustainability</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer-col\">\n");
      out.write("                <h4>Support</h4>\n");
      out.write("                <a href=\"#\">Help Center</a>\n");
      out.write("                <a href=\"#\">Shipping Info</a>\n");
      out.write("                <a href=\"#\">Returns</a>\n");
      out.write("                <a href=\"#\">Contact Us</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"footer-col\">\n");
      out.write("                <h4>Legal</h4>\n");
      out.write("                <a href=\"#\">Terms of Service</a>\n");
      out.write("                <a href=\"#\">Privacy Policy</a>\n");
      out.write("                <a href=\"#\">Cookie Policy</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"footer-bottom\">\n");
      out.write("            &copy; 2026 MyShop. All rights reserved.\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\r\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("// Hero slider\n");
      out.write("var heroCurrent = 0;\n");
      out.write("var heroTotal = 3;\n");
      out.write("var heroTimer;\n");
      out.write("\n");
      out.write("function heroGo(index) {\n");
      out.write("    heroCurrent = index;\n");
      out.write("    document.getElementById('heroSlider').style.transform = 'translateX(-' + (heroCurrent * 100) + '%)';\n");
      out.write("    document.querySelectorAll('.hero-dot').forEach(function(d, i) { d.classList.toggle('active', i === heroCurrent); });\n");
      out.write("}\n");
      out.write("function heroNext() { heroGo((heroCurrent + 1) % heroTotal); }\n");
      out.write("function heroPrev() { heroGo((heroCurrent - 1 + heroTotal) % heroTotal); }\n");
      out.write("\n");
      out.write("document.querySelectorAll('.hero-dot').forEach(function(d) {\n");
      out.write("    d.addEventListener('click', function() { heroGo(parseInt(this.dataset.index)); });\n");
      out.write("});\n");
      out.write("\n");
      out.write("heroTimer = setInterval(heroNext, 5000);\n");
      out.write("\n");
      out.write("// Touch swipe support\n");
      out.write("var touchStartX = 0;\n");
      out.write("document.getElementById('hero').addEventListener('touchstart', function(e) { touchStartX = e.touches[0].clientX; });\n");
      out.write("document.getElementById('hero').addEventListener('touchend', function(e) {\n");
      out.write("    var diff = touchStartX - e.changedTouches[0].clientX;\n");
      out.write("    if (Math.abs(diff) > 50) { diff > 0 ? heroNext() : heroPrev(); }\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("<script src=\"");
      out.print( request.getContextPath() );
      out.write("/js/global.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
